api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('', views.operations, name='operations'),

]

company/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('operations/', include('api.urls')),
    path('', include('core.urls')),
]
urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('company/',views.company, name='company'),
    path('branch/',views.branch, name='branch'),
    path('branch/create/', views.branch_create, name='branch_create'),
    path('branch/update/<int:pk>/',views.branch_update, name='branch_update'),
    path('branch/delete/<int:pk>/',views.branch_delete, name='branch_delete'),
    path('staff/',views.staff, name='staff'),
    path('employee/',views.employee, name='employee'),
    path('employee/create/', views.employee_create, name='employee_create'),
    path('employee/delete/<int:pk>/',views.employee_delete, name='employee_delete'),
    path('employee/update/<int:pk>',views.employee_update, name='employee_update'),
    path('employee/additional/<int:pk>',views.employee_additional, name='employee_additional'),
    path('search_results/', views.search_results, name="search_results"),

    path('edu/update/<int:pk>/', views.edu_update, name='edu_update'),
    path('edu/create/', views.edu_create, name='edu_create'),
    path('lang/update/<int:pk>/', views.lang_update, name='lang_update'),
    path('lang/create/', views.lang_create, name='lang_create'),
    path('exp/update/<int:pk>/', views.exp_update, name='exp_update'),
    path('exp/create/', views.exp_create, name='exp_create'),

    # path('auth/login/', views.auth_log_in, name='auth_log_in'),
    path('auth/signin/', views.auth_sign_in, name='auth_sign_in'),
    path('auth/logout/', views.auth_sign_out, name='auth_sign_out'),
    # path('auth/signin/', views.auth_sign_in, name='auth_sign_in'),
    path('auth/signup/', views.auth_sign_up, name='auth_sign_up'),
    path('users/', views.users, name = 'users'),
    path('password_update/', views.password_update, name = 'password_update'),
    path('user/delete/<int:pk>', views.user_delete, name = 'user_delete'),


    path('inbox/', views.inbox, name="inbox"),
    path('inbox/read', views.inbox_read, name="inbox_read"),
    path('inbox/unread', views.inbox_unread, name="inbox_unread"),
    path('inbox/detail/<int:pk>', views.inbox_detail, name="inbox_detail"),
    path('reply/<int:pk>', views.reply, name="reply"),
    path('sent/', views.sent, name="sent"),
    path('sent/detail/<int:pk>', views.sent_detail, name="sent_detail"),
    path('drafts/', views.drafts, name="drafts"),
    path('drafts/detail/<int:pk>', views.drafts_detail, name="drafts_detail"),
    path('trash/', views.trash, name="trash"),
    path('trash/detail/<int:pk>', views.trash_detail, name="trash_detail"),
    path('compose/', views.compose, name="compose"),
]

core/forms.py
from django import forms

from core import models

from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm



class UserForm(forms.ModelForm):

    class Meta:
        model = models.User
        fields = '__all__'

# ************************************************************************

class BranchForm(forms.ModelForm):

    class Meta:
        model = models.Branch
        fields = '__all__'

# ************************************************************************

class EmployeeForm(forms.ModelForm):

    class Meta:
        model = models.Employee
        fields = '__all__'

# ************************************************************************

class EmployeeEducationForm(forms.ModelForm):

    class Meta:
        model = models.EmployeeEducation
        fields = '__all__'

# ************************************************************************

class EmployeeLanguageForm(forms.ModelForm):

    class Meta:
        model = models.EmployeeLanguage
        fields = '__all__'

# ************************************************************************

class EmployeeExperienceForm(forms.ModelForm):

    class Meta:
        model = models.EmployeeExperience
        fields = '__all__'

# ************************************************************************

class MessageForm(forms.ModelForm):

    class Meta:
        model = models.Message
        fields = '__all__'

# ************************************************************************

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # email = models.Employee.objects.values('email')

    class Meta:
        model = models.User
        fields = ('username', 'email', 'password1', 'password2', )

# ************************************************************************

class PasswordForm(PasswordChangeForm):

    class Meta:
        model = models.User
        fields = '__all__'

# ************************************************************************

core/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect
from core import models, forms
from core.forms import SignUpForm, PasswordForm

from django.core.exceptions import ValidationError



def index(request):
    company = models.Companye.objects.all()
    if request.user.is_authenticated:
        return render(request, 'core/pages/index.html', {'company': company})
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def company(request):
    company = models.Companye.objects.all()
    if request.user.is_authenticated:
        return render(request, 'core/pages/company.html', {'company': company})
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def branch(request):
    branch = models.Branch.objects.filter(is_deleted=False)
    if request.user.is_authenticated:
        return render(request, 'core/pages/branch.html', {'branch': branch})
    else:
        return redirect('core:auth_sign_in')


# ****************************************************************************

def branch_create(request):
    form = forms.BranchForm
    if request.user.is_authenticated:
        if request.POST:
            form = forms.BranchForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Branch successfully added')
                return redirect('core:branch')
            else:
                messages.warning(request, 'Something was wrong, please try again')
                return redirect(request, 'core/pages/branch_create.html')
    else:
        return redirect('core:auth_sign_in')

    return render(request, 'core/pages/branch_create.html', {
        'form': form,
    })


# ****************************************************************************

def branch_update(request, pk):
    if not models.Branch.objects.filter(is_deleted=False).filter(pk=pk).exists():
        raise Http404
    branch = models.Branch.objects.filter(is_deleted=False).get(pk=pk)
    form = forms.BranchForm
    if request.user.is_authenticated:
        if request.POST:
            form = forms.BranchForm(request.POST, instance=branch)
            if form.is_valid():
                form.save()
                messages.success(request, 'Branch successfully updated')
                return redirect('core:branch')
            else:
                messages.warning(request, 'Something was wrong, please try again')
                return redirect('core:branch_update', branch.pk)
    else:
        return redirect('core:auth_sign_in')

    return render(request, 'core/pages/branch_update.html', {
        'branch': branch,
        'form': form,
    })


# ****************************************************************************

def branch_delete(request, pk):
    if not models.Branch.objects.filter(is_deleted=False).filter(pk=pk).exists():
        raise Http404
    if request.user.is_authenticated:
        branch = models.Branch.objects.filter(is_deleted=False).get(pk=pk)
        staffs_count = models.Staff.objects.filter(branch_id=branch.pk).count()
        if not staffs_count:
            messages.info(request, 'Deleted')
            branch.is_deleted = True
            branch.save()
        else:
            messages.warning(request, 'You can not  deleted this branch')
        return redirect('core:branch')
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def staff(request):
    branches = models.Branch.objects.all()

    if request.user.is_authenticated:
        return render(request, 'core/pages/staff.html', {'branches': branches})
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def employee(request):
    employees = models.Employee.objects.filter(is_deleted=False)
    if request.user.is_authenticated:
        return render(request, 'core/pages/employee.html', {
            'employees': employees,
        })
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def employee_delete(request,pk):
    if not models.Employee.objects.filter(is_deleted=False).filter(pk=pk).exists():
        raise Http404
    if request.user.is_authenticated:
        employee = models.Employee.objects.filter(is_deleted=False).get(pk=pk)
        employee.is_deleted = True
        employee.save()
        messages.info(request,'Employee deleted')
        return redirect('core:employee')
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def employee_create(request):
    gender = models.Gender.objects.all()
    staff = models.Staff.objects.all()
    staff_type = models.StaffType.objects.all()
    form = forms.EmployeeForm
    if request.user.is_authenticated:
        if request.POST:
            form = forms.EmployeeForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Employee successfully added')
                return redirect('core:employee')
            else:
                messages.warning(request,'Something was wrong, please try again')
                return redirect(request, 'core/pages/employee_create.html')
        return render(request,'core/pages/employee_create.html',{
            'gender' : gender,
            'staff' : staff,
            'staff_type' : staff_type,
            'form': form,
        })
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def employee_update(request,pk):
    if not models.Employee.objects.filter(is_deleted=False).filter(pk=pk).exists():
        raise Http404
    employee = models.Employee.objects.filter(is_deleted=False).get(pk=pk)
    gender = models.Gender.objects.all()
    staff = models.Staff.objects.all()
    staff_type = models.StaffType.objects.all()
    form = forms.EmployeeForm
    if request.user.is_authenticated:
        if request.POST:
            form = forms.EmployeeForm(request.POST, instance=employee)
            if form.is_valid():
                form.save()
                messages.success(request, 'Employee information successfully updated')
                return redirect('core:employee')
            else:
                messages.warning(request, 'Something was wrong, please try again')
                return redirect('core:employee_update', employee.pk)
    else:
        return redirect('core:auth_sign_in')

    return render(request, 'core/pages/employee_update.html', {
        'gender': gender,
        'staff': staff,
        'staff_type' : staff_type,
        'form': form,
        'pk': pk,
        'employee' : employee,
    })

# ****************************************************************************

def employee_additional(request,pk):
    if not models.Employee.objects.filter(is_deleted=False).filter(pk=pk).exists():
        raise Http404
    if request.user.is_authenticated:
        about = models.Employee.objects.filter(is_deleted=False).get(pk=pk)
        edu_info = models.EmployeeEducation.objects.filter(employee_id__pk=pk).order_by('-edu_from_date')
        lang_info = models.EmployeeLanguage.objects.filter(emplooyee__pk=pk).order_by('-certificate_date')
        exp_info = models.EmployeeExperience.objects.filter(employee__pk=pk).order_by('-exp_from_date')
        return render(request,'core/pages/employee_additional.html',{
            'pk':pk,
            'edu_info':edu_info,
            'about':about,
            'lang_info':lang_info,
            'exp_info':exp_info,
        })
    else:
        return redirect('core:auth_sign_in')

# ****************************************************************************

def edu_update(request,pk):
    if not models.EmployeeEducation.objects.filter(pk=pk).exists():
        raise Http404
    edu_info = models.EmployeeEducation.objects.get(pk=pk)
    education_type = models.EducationType.objects.all()
    about = models.Employee.objects.filter(email=edu_info.employee_id.email)

    form = forms.EmployeeEducationForm
    if request.user.is_authenticated:
        if request.POST:
            form = forms.EmployeeEducationForm(request.POST, instance=edu_info)
            if form.is_valid():
                form.save()
                messages.success(request, 'Education information successfully updated')
                return redirect('core:employee_additional', edu_info.employee_id.pk)
            else:
                messages.warning(request, 'Something was wrong, please try again')
                return redirect('core:edu_update', edu_info.pk)
    else:
        return redirect('core:auth_sign_in')

    return render(request, 'core/pages/additional_changes/edu_update.html', {
        'form': form,
        'pk': pk,
        'edu_info':edu_info,
        'education_type':education_type,
        'about':about,
    })

# ****************************************************************************

def edu_create(request):
    about = models.Employee.objects.filter(email=request.user.email)
    education_type = models.EducationType.objects.all()
    form = forms.EmployeeEducationForm
    if request.user.is_authenticated:
        if request.POST:
            form = forms.EmployeeEducationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Education information successfully added')
                return redirect('core:edu_create')
            else:

core/templates/core/pages/users/password_update.html
{% extends 'core/layout/base.html' %}
{% block main %}
<body>
<section class="body">
    <div class="inner-wrapper">
        <section role="main" class="content-body pb-0">
            <header class="page-header">
                <h2>User password update</h2>
                <div class="right-wrapper text-right">
                    <ol class="breadcrumbs">
                        <li>
                            <a href="{% url 'core:company' %}">
                                <i class="fas fa-home"></i>
                            </a>
                        </li>
                        <li><span>User password update</span></li>
                    </ol>
                    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
                </div>
            </header>
            <div class="col-lg-8 mx-auto">
                <main>
                    <form method="post" class="form-horizontal form-bordered">
                        {% csrf_token %}
                        <section class="card">
                            <header class="card-header">
                                <div class="card-actions">
                                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                                </div>
                                <h2 class="card-title">Update {{ request.user.username }}'s password</h2>
                            </header>
                            <div class="card-body">

                                <div class="form-group row">
                                    <label for="old_password" class="col-sm-4 control-label text-sm-right pt-2">Old password:</label>
                                    <div class="col-sm-8">
                                        <input type="password" id="old_password" name="old_password" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="new_password1" class="col-sm-4 control-label text-sm-right pt-2">New password:</label>
                                    <div class="col-sm-8">
                                        <input type="password" id="new_password1" name="new_password1" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="new_password2" class="col-sm-4 control-label text-sm-right pt-2"> New password again:</label>
                                    <div class="col-sm-8">
                                        <input type="password" id="new_password2" name="new_password2" class="form-control">
                                    </div>
                                </div>

                            </div>
                            <footer class="card-footer text-right">
                                <button class="btn btn-info" type="submit">Submit</button>
                                <button class="btn btn-secondary"><a href="{% url 'core:users' %}">Cancel</a></button>
                            </footer>
                        </section>
                    </form>
                </main>
            </div>
        </section>
    </div>
</section>
</body>
{% endblock %}

core/templates/core/pages/users/users.html
{% extends 'core/layout/base.html' %}
{% block main %}
<body>
<section class="body">
    <div class="inner-wrapper">
        <section role="main" class="content-body pb-0">
            <header class="page-header">
                <h2>Users</h2>
                <div class="right-wrapper text-right">
                    <ol class="breadcrumbs">
                        <li>
                            <a href="{% url 'core:company' %}">
                                <i class="fas fa-home"></i>
                            </a>
                        </li>
                        <li><span>Users</span></li>
                    </ol>
                    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
                </div>
            </header>
            <div class="container">
                <table class="table table-responsive-md table-success  mb-0">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Date joined</th>
                        <th>Last login</th>
                        <th>is_staff</th>
                        <th>is_active</th>
                        <th>is_superuser</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ request.user.pk }}</td>
                            <td>{{ request.user.username }}</td>
                            <td>{{ request.user.email }}</td>
                            <td>{{ user.date_joined }}</td>
                            <td>{{ user.last_login }}</td>
                            <td>{{ user.is_staff }}</td>
                            <td>{{ user.is_active }}</td>
                            <td>{{ user.is_superuser }}</td>
                            <td class="actions-hover actions-fade">
                                <a href="{% url 'core:password_update' %}"><i class="fas fa-pencil-alt"
                                                                              style="color:green"></i></a>
                                <a href="{% url 'core:user_delete' request.user.pk %}" class="delete-row"><i
                                        class="far fa-trash-alt" style="color:green"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</section>
</body>
{% endblock %}
{% block js %}
<script>
	 $('.delete-row').on('click',function(event){
	 	event.preventDefault();

        let confirm = window.confirm('Are you sure?');
        if (confirm) {
			window.location.href = $(this).attr('href');
		}
    });

</script>
{% endblock %}